name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0

    - name: Install LaTeX
      run: sudo apt-get -y install -qq texlive-fonts-recommended texlive-latex-recommended

    - name: Check bibtex files
      run: |
        ./tests/run-tests.sh
